/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_michaeldenk_yasdi4j_YasdiChannel_Type */

#ifndef _Included_de_michaeldenk_yasdi4j_YasdiChannel_Type
#define _Included_de_michaeldenk_yasdi4j_YasdiChannel_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
