/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_michaeldenk_yasdi4j_YasdiChannel */

#ifndef _Included_de_michaeldenk_yasdi4j_YasdiChannel
#define _Included_de_michaeldenk_yasdi4j_YasdiChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_michaeldenk_yasdi4j_YasdiChannel
 * Method:    c_updateValue
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_michaeldenk_yasdi4j_YasdiChannel_c_1updateValue
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
